spring:
  application:
    name: http-cache

logging:
  level:
    com.acme.httpcache: INFO
    org.springframework.aop.framework: DEBUG
    org.springframework.aop.framework.JdkDynamicAopProxy: DEBUG
  appenders:
    - type: console
      logFormat: "%-5p [%d{ISO8601,UTC}] [trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}] %c: %m [%t]%n%rEx"
      
crnk:
  resourcePackage: com.acme.httpcache
  domainName: http://localhost:8080
  pathPrefix: /v1
